// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Globalization", "CA1305:IFormatProvider を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Rest.FileController.FileDownloadAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Globalization", "CA1305:IFormatProvider を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Rest.FileController.CsvDownloadAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Globalization", "CA1307:StringComparison を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Globalization", "CA1307:StringComparison を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Util.CsvUtil.ReadCsv(System.Collections.Generic.Dictionary{System.String,System.String},System.Collections.Generic.List{System.String},System.String,System.String@)~System.Collections.Generic.List{SKYCOM.DLManagement.Entity.User}")]
[assembly: SuppressMessage("Globalization", "CA1307:StringComparison を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.GmailAPI.GmailSendByAPI.ExecGmailSend(SKYCOM.DLManagement.Data.MailInfo)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1304:CultureInfo を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Util.CsvUtil.ReadCsv(System.Collections.Generic.Dictionary{System.String,System.String},System.Collections.Generic.List{System.String},System.String,System.String@)~System.Collections.Generic.List{SKYCOM.DLManagement.Entity.User}")]
[assembly: SuppressMessage("Performance", "CA1822:メンバーを static に設定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.FileManagementService.GetServerFileInfos(SKYCOM.DLManagement.Data.ServerFileInfo)~System.Threading.Tasks.Task{System.Collections.Generic.List{SKYCOM.DLManagement.Data.ServerFileInfo}}")]
[assembly: SuppressMessage("Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Int32)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.GmailAPI.GmailSendByAPI.ExecGmailSend(SKYCOM.DLManagement.Data.MailInfo)~System.Boolean")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Rest.FileController.FileDownloadAsync(System.String)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Rest.FileController.FileUpload(Microsoft.AspNetCore.Http.IFormFile)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Rest.FileController.CsvDownloadAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Util.CsvUtil.ReadCsv(System.Collections.Generic.Dictionary{System.String,System.String},System.Collections.Generic.List{System.String},System.String,System.String@)~System.Collections.Generic.List{SKYCOM.DLManagement.Entity.User}")]
[assembly: SuppressMessage("Design", "CA1052:スタティック ホルダー型は Static または NotInheritable でなければなりません", Justification = "<保留中>", Scope = "type", Target = "~T:SKYCOM.DLManagement.Program")]
[assembly: SuppressMessage("Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.GmailAPI.GmailSendByAPI.ExecGmailSend(SKYCOM.DLManagement.Data.MailInfo)~System.Boolean")]
[assembly: SuppressMessage("Globalization", "CA1307:StringComparison を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Globalization", "CA1305:IFormatProvider を指定します", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Usage", "CA2227:コレクション プロパティは読み取り専用でなければなりません", Justification = "<保留中>", Scope = "member", Target = "~P:SKYCOM.DLManagement.Data.MailInfo.DLStatusManagementIds")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SelectProduct(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.CreateDownloadUrl(System.Collections.Generic.List{SKYCOM.DLManagement.Entity.User},System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo},System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl}}")]
[assembly: SuppressMessage("Design", "CA1062:パブリック メソッドの引数の検証", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Performance", "CA1806:メソッドの結果を無視しない", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.SendMail(System.Collections.Generic.List{SKYCOM.DLManagement.Data.DownloadUrl},System.Nullable{System.DateTime},System.String,System.String,System.Collections.Generic.List{SKYCOM.DLManagement.Data.ProductInfo})~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Reliability", "CA2000:スコープを失う前にオブジェクトを破棄", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Util.LogUtil.#ctor")]
[assembly: SuppressMessage("Usage", "CA2227:コレクション プロパティは読み取り専用でなければなりません", Justification = "<保留中>", Scope = "member", Target = "~P:SKYCOM.DLManagement.Data.Settings.TemplateList")]
[assembly: SuppressMessage("Usage", "CA2227:コレクション プロパティは読み取り専用でなければなりません", Justification = "<保留中>", Scope = "member", Target = "~P:SKYCOM.DLManagement.Data.Settings.ProductList")]
[assembly: SuppressMessage("Usage", "CA2227:コレクション プロパティは読み取り専用でなければなりません", Justification = "<保留中>", Scope = "member", Target = "~P:SKYCOM.DLManagement.Data.Settings.CsIpAddress")]
[assembly: SuppressMessage("Usage", "CA2227:コレクション プロパティは読み取り専用でなければなりません", Justification = "<保留中>", Scope = "member", Target = "~P:SKYCOM.DLManagement.Data.Csv.CsCsvExclusion")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.InitMailText~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Design", "CA1031:一般的な例外の種類はキャッチしません", Justification = "<保留中>", Scope = "member", Target = "~M:SKYCOM.DLManagement.Services.ReleaseGuideService.ExecGmailSendAll(System.Object)")]
